@startuml
title SmartPark - Diagrama de Classes

' =========================
' ENUMS
' =========================

enum Role {
    ADMIN_GLOBAL
    ADMIN_UNIDADE
    FISCAL
    USUARIO
}

enum TipoUsuario {
    ALUNO
    PROFESSOR
    FUNCIONARIO
    VISITANTE
}

enum TipoEstacionamento {
    ALUNO
    PROFESSOR
    MISTO
    VISITANTE
    PCD
}

enum StatusVaga {
    LIVRE
    OCUPADA
    RESERVADA
    INDISPONIVEL
}

enum TipoInfracao {
    MULTIPLAS_VAGAS
    USO_INDEVIDO_PCD
    AREA_PROIBIDA
    VAGA_NAO_AUTORIZADA
}

enum TipoSensor {
    RFID
    CAMERA
    ULTRASSOM
    OBD
}

' =========================
' USUÁRIOS
' =========================

class User {
    -Long id
    -String nome
    -String email
    -String senha

    +autenticar()
    +alterarSenha()
}

class Veiculo {
    -Long id
    -String placa
    -String modelo
    -String cor
    -Boolean pcd
}

User --> Role
User --> TipoUsuario

User "1" *-- "*" Veiculo

' =========================
' ESTRUTURA CAMPUS
' =========================

class Unidade {
    -Long id
    -String nome
    -String endereco
}

class Estacionamento {
    -Long id
    -String nome
    -Integer capacidade
}

class Vaga {
    -Long id
    -String codigo
    -Boolean preferencial
}

Estacionamento --> TipoEstacionamento
Vaga --> StatusVaga

Unidade "1" *-- "*" Estacionamento
Estacionamento "1" *-- "*" Vaga

' =========================
' ACESSO
' =========================

class Acesso {
    -Long id
    -Date entrada
    -Date saida
    -String placaDetectada
}

User "1" -- "*" Acesso
Veiculo "1" -- "*" Acesso
Estacionamento "1" -- "*" Acesso

' =========================
' IOT
' =========================

class Sensor {
    -Long id
    -Boolean ativo
}

class GatewayEdge {
    -Long id
    -String ip
    -Boolean online
}

class EventoIoT {
    -Long id
    -String tipoEvento
    -Date timestamp
}

Sensor --> TipoSensor

Vaga "1" *-- "*" Sensor
GatewayEdge "1" -- "*" Sensor
Sensor "1" -- "*" EventoIoT

' =========================
' INFRAÇÕES
' =========================

class Infracao {
    -Long id
    -String descricao
    -Date dataHora
    -Boolean resolvida
}

Infracao --> TipoInfracao

User "1" -- "*" Infracao
Veiculo "1" -- "*" Infracao
Vaga "1" -- "*" Infracao

' =========================
' NOTIFICAÇÕES
' =========================

class Notificacao {
    -Long id
    -String mensagem
    -Date dataEnvio
    -Boolean visualizada
}

User "1" -- "*" Notificacao

@enduml