@startuml
title SmartPark - Diagrama de Classes

skinparam classBackgroundColor #E8F4FD
skinparam classBorderColor #2E86AB
skinparam ArrowColor #333333

enum Role {
    ADMIN_GLOBAL
    ADMIN_UNIDADE
    FISCAL
    USUARIO
}
enum TipoUsuario {
    ALUNO
    PROFESSOR
    FUNCIONARIO
    VISITANTE
}
enum TipoEstacionamento {
    ALUNO
    PROFESSOR
    MISTO
    VISITANTE
    PCD
}
enum StatusVaga {
    LIVRE
    OCUPADA
    RESERVADA
    INDISPONIVEL
}
enum TipoInfracao {
    MULTIPLAS_VAGAS
    USO_INDEVIDO_PCD
    AREA_PROIBIDA
    VAGA_NAO_AUTORIZADA
}
enum TipoSensor {
    RFID
    CAMERA
    ULTRASSOM
    OBD
}


class User {
    -Long id
    -String nome
    -String email
    -String senha
    -Role role
    -TipoUsuario tipo
    +autenticar()
    +alterarSenha()
}
class Veiculo {
    -Long id
    -String placa
    -String modelo
    -String cor
    -Boolean pcd
}

User "1" *-- "*" Veiculo : possui


class Unidade {
    -Long id
    -String nome
    -String endereco
}
class Estacionamento {
    -Long id
    -String nome
    -Integer capacidade
    -TipoEstacionamento tipo
}
class Vaga {
    -Long id
    -String codigo
    -Boolean preferencial
    -StatusVaga status
}

Unidade "1" *-- "*" Estacionamento : contém
Estacionamento "1" *-- "*" Vaga : contém


class Acesso {
    -Long id
    -Date entrada
    -Date saida
    -String placaDetectada
    +registrarEntrada()
    +registrarSaida()
    +calcularDuracao()
}

User "1" -- "*" Acesso : realiza
Veiculo "1" -- "*" Acesso : identificado em
Estacionamento "1" -- "*" Acesso : ocorre em


class Sensor {
    -Long id
    -TipoSensor tipo
    -Boolean ativo
    +capturarEvento()
}
class GatewayEdge {
    -Long id
    -String ip
    -Boolean online
    +sincronizar()
}
class EventoIoT {
    -Long id
    -String tipoEvento
    -Date timestamp
    +processar()
}

Vaga "1" *-- "*" Sensor      : monitorada por
Unidade "1" -- "*" GatewayEdge : instalado em
GatewayEdge "1" -- "*" Sensor  : gerencia
Sensor "1" -- "*" EventoIoT   : gera
EventoIoT "*" -- "1" Vaga      : refere-se a

class Infracao {
    -Long id
    -TipoInfracao tipo
    -String descricao
    -Date dataHora
    -Boolean resolvida
    +registrar()
    +resolver()
}

Acesso "1" -- "*" Infracao   : origina
Veiculo "1" -- "*" Infracao  : envolvido em
Vaga "1" -- "*" Infracao     : ocorre em


class Notificacao {
    -Long id
    -String mensagem
    -Date dataEnvio
    -Boolean visualizada
    +enviar()
    +marcarComoLida()
}

User "1" -- "*" Notificacao    : recebe
Infracao "1" -- "*" Notificacao : gera

@enduml